### PR TITLE
packaging: use numpy distutils and streamline setup scripts

### PR DESCRIPTION
**Pull request by jakevdp**
In progress PR:

My goal here is to simplify the build step – rather than having to build cyflann separately, this builds it as a submodule extension. ~~I've still not been able to install the package on my Mac, despite having three working installations of FLANN (one from homebrew, one from conda, one from source). Installation is fine, but I'm getting dylib linking errors at runtime and have spent several hours trying to figure out how to fix them.~~

The build now works for me on OSX, using flann installed by anaconda. Linux should work as well: if so I'll update the documentation and merge this.

### CODE REVIEW

**Comment by jakevdp** [comment]
One question for @Jerryzcn – what version of flann are you using when you build this? The runtime error I'm getting is this:
```pytb
In [1]: from Mmani import geometry
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-95e2c0b7f5d5> in <module>()
----> 1 from Mmani import geometry

/Users/jakevdp/anaconda/envs/Mmani-dev/lib/python2.7/site-packages/Mmani/geometry/__init__.py in <module>()
      1 from .rmetric import RiemannMetric
----> 2 from .geometry import Geometry

/Users/jakevdp/anaconda/envs/Mmani-dev/lib/python2.7/site-packages/Mmani/geometry/geometry.py in <module>()
     35 from scipy.spatial.distance import pdist
     36 import subprocess, os, sys, warnings
---> 37 from Mmani.geometry.distance import distance_matrix
     38 from Mmani.utils.validation import check_array
     39 

/Users/jakevdp/anaconda/envs/Mmani-dev/lib/python2.7/site-packages/Mmani/geometry/distance.py in <module>()
      6 from scipy import sparse
      7 from scipy.spatial.distance import pdist
----> 8 from Mmani.geometry.cyflann.index import Index
      9 import subprocess, os, sys, warnings
     10 

ImportError: dlopen(/Users/jakevdp/anaconda/envs/Mmani-dev/lib/python2.7/site-packages/Mmani/geometry/cyflann/index.so, 2): Symbol not found: _LZ4_compress_HC_continue
  Referenced from: /Users/jakevdp/anaconda/envs/Mmani-dev/lib/python2.7/site-packages/Mmani/geometry/cyflann/index.so
  Expected in: /usr/local/lib/libflann_cpp.1.8.dylib
 in /Users/jakevdp/anaconda/envs/Mmani-dev/lib/python2.7/site-packages/Mmani/geometry/cyflann/index.so
```
This symbol seems to be something related to the Lz4 library that was added in the last few commits to the FLANN repo: https://github.com/mariusmuja/flann/tree/master/src/cpp/flann/ext/

**Comment by Jerryzcn** [comment]
@jakevdp I am using flann-1.8.4-src, which can be downloaded from github or the flann website `http://www.cs.ubc.ca/research/flann/uploads/FLANN/flann-1.8.4-src.zip`. You will need to unzip and compile it, once u downloaded it. Also If u already have a version of flann in the system, it may cause error during build time. If u use conda to install flann, it might install 1.8.5dev. I have tested 1.8.5dev before, but later removed it, and switch back to 1.8.4. Do u have this problem if u build it from /Mmani/geometry/cyflann ?

**Comment by jakevdp** [comment]
Yes, I had the same problem when I used the two-phase build. I was tired of the multi-step build process when trying to debug the problem; that's why I changed it here so that a single ``setup.py install`` takes care of the whole package :smile:

What was the problem you were having with 1.8.5.dev?

**Comment by jakevdp** [comment]
(Also, eventually we will want the simplest possible install instructions, so I'd vote to merge something like this PR even if I can't get the installation working on my machine).

**Comment by Jerryzcn** [comment]
@jakevdp I decided not to use 1.8.5dev simply because it is dev version not stable version. For building 1.8.4, I basically conda uninstall flann and build the 1.8.4.
I would assume upgrading to 1.8.5dev should works fine though, as long as the runtime and the build is based on 1.8.5dev. Are u using 1.8.5dev?

**Comment by jakevdp** [comment]
I was trying both, but I found the problem was a different one. There is an issue with dynamic linking in OSX, and I had to add an extra step to the setup.py to make it work.

With this change, I'm able to install the library on my laptop by running
```
$ cd Mmani
$ conda install -c http://conda.binstar.org/dougal flann numpy scipy
$ python setup.py install
```
Can you check whether this works on your linux machine? If it does then we can go a step further and make Mmani also installable via conda, so it can all be done in one line!

**Comment by Jerryzcn** [comment]
It can build, but when I import, I got this:

>>> from Mmani import geometry
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Mmani/geometry/__init__.py", line 2, in <module>
    from .geometry import Geometry
  File "Mmani/geometry/geometry.py", line 37, in <module>
    from Mmani.geometry.distance import distance_matrix
  File "Mmani/geometry/distance.py", line 8, in <module>
    from Mmani.geometry.cyflann.index import Index
ImportError: No module named index

**Comment by jakevdp** [comment]
My guess is that you did ``python setup.py install`` and then ran Python from within the source tree. You can either

1. Use ``python setup.py build_ext --inplace`` to build the source inplace or
2. Change to another directory and then try the import again

Let me know if that works

**Comment by jakevdp** [comment]
I added some functionality that will give a more useful error when trying to import from the source tree.

**Comment by Jerryzcn** [comment]
@jakevdp Worked!

**Comment by jakevdp** [comment]
Great to hear! Are you comfortable merging this then? Maybe we should let @jmcq89 take a look and push the green button?

**Comment by jmcq89** [comment]
Seems good to me. I'll merge the pull request.

**Pull request merged**
